#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebReport1.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="aspnet-WebReport1-20200622011138")]
	public partial class MyDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public MyDataDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["aspnet_WebReport1_20200622011138ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TienDoCBQL> TienDoCBQLs
		{
			get
			{
				return this.GetTable<TienDoCBQL>();
			}
		}
		
		public System.Data.Linq.Table<TienDoMLN> TienDoMLNs
		{
			get
			{
				return this.GetTable<TienDoMLN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TienDoCBQL")]
	public partial class TienDoCBQL
	{
		
		private string _TT;
		
		private string _MA;
		
		private string _CHITIEU;
		
		private System.Nullable<decimal> _THANG;
		
		private System.Nullable<decimal> _QUY;
		
		private System.Nullable<decimal> _NAM;
		
		private System.Nullable<decimal> _KHQUY;
		
		private System.Nullable<decimal> _KHNAM;
		
		public TienDoCBQL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TT", DbType="VarChar(3)")]
		public string TT
		{
			get
			{
				return this._TT;
			}
			set
			{
				if ((this._TT != value))
				{
					this._TT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA", DbType="VarChar(50)")]
		public string MA
		{
			get
			{
				return this._MA;
			}
			set
			{
				if ((this._MA != value))
				{
					this._MA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHITIEU", DbType="NVarChar(200)")]
		public string CHITIEU
		{
			get
			{
				return this._CHITIEU;
			}
			set
			{
				if ((this._CHITIEU != value))
				{
					this._CHITIEU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANG", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> THANG
		{
			get
			{
				return this._THANG;
			}
			set
			{
				if ((this._THANG != value))
				{
					this._THANG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUY", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> QUY
		{
			get
			{
				return this._QUY;
			}
			set
			{
				if ((this._QUY != value))
				{
					this._QUY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAM", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> NAM
		{
			get
			{
				return this._NAM;
			}
			set
			{
				if ((this._NAM != value))
				{
					this._NAM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KHQUY", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> KHQUY
		{
			get
			{
				return this._KHQUY;
			}
			set
			{
				if ((this._KHQUY != value))
				{
					this._KHQUY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KHNAM", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> KHNAM
		{
			get
			{
				return this._KHNAM;
			}
			set
			{
				if ((this._KHNAM != value))
				{
					this._KHNAM = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TienDoMLNS")]
	public partial class TienDoMLN
	{
		
		private string _TT;
		
		private string _MA;
		
		private string _CHITIEU;
		
		private System.Nullable<decimal> _THANG;
		
		private System.Nullable<decimal> _QUY;
		
		private System.Nullable<decimal> _NAM;
		
		private System.Nullable<decimal> _KHQUY;
		
		private System.Nullable<decimal> _KHNAM;
		
		public TienDoMLN()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TT", DbType="VarChar(3)")]
		public string TT
		{
			get
			{
				return this._TT;
			}
			set
			{
				if ((this._TT != value))
				{
					this._TT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA", DbType="VarChar(50)")]
		public string MA
		{
			get
			{
				return this._MA;
			}
			set
			{
				if ((this._MA != value))
				{
					this._MA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHITIEU", DbType="NVarChar(200)")]
		public string CHITIEU
		{
			get
			{
				return this._CHITIEU;
			}
			set
			{
				if ((this._CHITIEU != value))
				{
					this._CHITIEU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANG", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> THANG
		{
			get
			{
				return this._THANG;
			}
			set
			{
				if ((this._THANG != value))
				{
					this._THANG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUY", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> QUY
		{
			get
			{
				return this._QUY;
			}
			set
			{
				if ((this._QUY != value))
				{
					this._QUY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAM", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> NAM
		{
			get
			{
				return this._NAM;
			}
			set
			{
				if ((this._NAM != value))
				{
					this._NAM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KHQUY", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> KHQUY
		{
			get
			{
				return this._KHQUY;
			}
			set
			{
				if ((this._KHQUY != value))
				{
					this._KHQUY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KHNAM", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> KHNAM
		{
			get
			{
				return this._KHNAM;
			}
			set
			{
				if ((this._KHNAM != value))
				{
					this._KHNAM = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
